export const GET_SELLER_INPUT = "GET_SELLER_INPUT";
export const AFTER_CREATE_SELLER = "AFTER_CREATE_SELLER";
export const IS_CREATE_SELLER = "IS_CREATE_SELLER";
export const SELLER_LIST = "SELLER_LIST";
export const AFTER_DELETED = "AFTER_DELETED";
