export const IS_CREATE_BRAND = "IS_CREATE_BRAND";
export const BRAND_LIST = "BRAND_LIST";
export const AFTER_CREATED = "AFTER_CREATED";
export const AFTER_DELETED = "AFTER_DELETED";
export const AFTER_UPDATED = "AFTER_UPDATED";
export const IS_UPDATE_BRAND = "IS_UPDATE_BRAND";
