export const IS_CREATE_SUBCATEGORY = "IS_CREATE_SUBCATEGORY";
export const SUBCATEGORY_LIST = "SUBCATEGORY_LIST";
export const AFTER_CREATED = "AFTER_CREATED";
export const AFTER_DELETED = "AFTER_DELETED";
